server:
  port: 8081

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;
    username: SA
    password: ${DB_SENHA_MARCAPAGINA}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${app.conf.keycloak.auth}/realms/marca-pagina/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            jwk-set-uri: ${app.conf.keycloak.auth}/realms/marca-pagina/protocol/openid-connect/certs
            issuer-uri: ${app.conf.keycloak.auth}/realms/marca-pagina
            user-name-attribute: preferred_username

app:
  conf:
    capas:
      dir: ${java.io.tmpdir}/fotos
    keycloak:
      auth: http://localhost:8080/auth