server:
  port: 8081
  base-path: /marcapagina

jwt:
  secret: ${JWT_SECRET}

spring:
  main:
    allow-circular-references: true

app:
  conf:
    datasource:
      marcapagina:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        jdbc-url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;
        username: SA
        password: ${DB_SENHA_MARCAPAGINA}